version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=travila
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  # Backend (Node.js / Express) service
  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/travila
      - PORT=3001
      - NODE_ENV=development
      - JWT_EXPIRES_IN=30d
      - JWT_SECRET=b741773ad1a181dcbda38ca6cec2dbee33258ea0f3bc7f740211ffcd4f68de99992a88e838949e084025b8df0f381797d93576bac8884478ac93047bd49ca003102c29274546f1d0a50b764fe3cdf26c39d2224fea3d0941396178a17575e69b2728f078d466e05c42452bc74af487d4ef3215f34492408bcda1659aa38d60e225d18500096e06e375694b3ec34e5678d6e1653c9446b4c4c57eb3c1a4b86d5cf98720ed98a4729a738a4c78a305e0d69094bbe8afae9a963b802035d72f2a7f1c65423d133ed2f0bade66cf9726c703d31399434e0caef07a9c6c85f988083176679a4a4277a182f1afbee7c4ec7c416eb24528d16fa5099d7b0f4d4cbbf77b
    ports:
      - "3001:3001"  # Your backend API will be on port 3001
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app_network

  # Frontend (React app) service
  frontend:
    build: ./front-end
    container_name: frontend
    environment:
      # - NEXT_PUBLIC_API_URL=http://localhost:3001  # Change the port to 3001 to match the backend
      - NEXT_PUBLIC_API_URL=https://3001-alibenhenia-gomorocco-j0u1o1gy5ny.ws-eu120.gitpod.io  # Change the port to 3001 to match the backend
    ports:
      - "3000:3000"  # Your frontend will be on port 3000
    depends_on:
      - backend
    volumes:
      - ./front-end:/app
      - /app/node_modules  # This ensures node_modules stays inside the container
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
